Inference deployment on Openshift and move to 1.15
kubesecurity/openshift-probable-vulnerabilities pull request #18
Opened 2020-02-19 06:43 UTC by rootAvish

2020-02-24 04:18 UTC, rajusem reviewed
Added 2 minor comments.

2020-02-24 04:18 UTC, rajusem commented on deployment/Dockerfile
> +RUN yum install -y git rh-python36 && source /opt/rh/rh-python36/enable && python -m pip install --upgrade pip virtualenv setuptools
Split this line for easy readability without scroll.

2020-02-24 04:18 UTC, rajusem commented on model_inference_triage_pipeline/run_model_inference.py
> +            filtered_security_encoded_docs, batch_size=64, verbose=0)
We can read batch_size from param, that way we don't need to change our code if we need to change it's value.

2020-02-24 07:27 UTC, arajkumar commented on deployment/README.md
> +processing will move to the GPU, otherwise everything proceeds as normal on the GPU.
> otherwise everything proceeds as normal on the GPU.
It should be "CPU" right?

2020-02-24 08:53 UTC, arajkumar commented on deployment/README.md
> +get you the appropriate error message from the namespace.
It would be good to have some info on where it stores the inference results.

2020-02-24 17:49 UTC, arajkumar requested changes

2020-02-24 17:49 UTC, arajkumar commented on deployment/template-cronjob.yaml
> +  value: 14
value must be a string.

2020-02-24 17:49 UTC, arajkumar commented on deployment/template-cronjob.yaml
> +  required: True
follow consistent value for `required` attribute. At some places camel case has used.

2020-02-24 17:49 UTC, arajkumar commented on deployment/template-job.yaml
> +  value: 14
ditto

2020-02-24 17:49 UTC, arajkumar commented on deployment/template-service.yaml
> +  value: 14
ditto

2020-02-24 17:49 UTC, arajkumar commented on deployment/template-service.yaml
> +  value: "INFO"
Remove Unused params

2020-02-25 08:40 UTC, rootAvish commented
@rajusem @arajkumar Took care of the changes you guys requested, please have a look again.

2020-02-25 12:41 UTC, rajusem approved these changes
LGTM

2020-02-28 07:09 UTC, rootAvish commented
@arajkumar Let me know if your have any other comments, else I can merge.

2020-03-02 08:33 UTC, arajkumar approved these changes
lgtm.

2020-03-02 08:33 UTC, merged